# Generated by Django 4.1.2 on 2022-12-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='subtask',
            new_name='subtask1',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='task',
            new_name='subtask2',
        ),
        migrations.AddField(
            model_name='post',
            name='subtask3',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='task1',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='task2',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='task3',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='task4',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='task5',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='task6',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
    ]
