# Generated by Django 4.1.2 on 2022-12-31 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_status_alter_post_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraggableState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_id', models.CharField(max_length=255)),
                ('new_position', models.PositiveIntegerField()),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SubTask',
        ),
    ]
