# Generated by Django 4.1.2 on 2022-12-31 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_draggablestate_modified_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_id', models.CharField(max_length=255)),
                ('list_name', models.CharField(max_length=255)),
                ('position', models.PositiveIntegerField()),
            ],
        ),
    ]
