# Generated by Django 4.1.2 on 2023-01-01 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_listitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='subtask1',
            new_name='subtask',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='task1',
            new_name='task',
        ),
    ]
