# Generated by Django 4.1.2 on 2023-01-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_rename_status_post_status1_post_status2_post_status3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='status2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='status3',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='status4',
            field=models.CharField(max_length=100),
        ),
    ]
