# Generated by Django 4.1.2 on 2023-01-03 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_post_status1_alter_post_status2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListItem',
        ),
    ]
