# Generated by Django 4.1.2 on 2023-01-03 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_delete_listitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='item',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created',
        ),
    ]
