# Generated by Django 4.1.2 on 2023-01-03 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_rename_item_task_name_remove_task_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DraggableState',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
