# Generated by Django 4.1.2 on 2023-01-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_remove_post_subtask1_remove_post_subtask2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tasks',
            field=models.TextField(),
        ),
    ]
