# Generated by Django 4.1.2 on 2023-01-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_post_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='contributor',
        ),
        migrations.AddField(
            model_name='post',
            name='contributor',
            field=models.CharField(default='collab', max_length=100),
            preserve_default=False,
        ),
    ]
