# Generated by Django 4.1.2 on 2023-01-05 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_remove_post_assign_task_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='contributor',
            new_name='collaborator',
        ),
    ]
