# Generated by Django 4.1.2 on 2023-01-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_rename_contributor_post_collaborator'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='assign_task_to',
            field=models.TextField(default='Assignation'),
            preserve_default=False,
        ),
    ]
